apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: svc-openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:00B+keq+m6k7ORvrlgs1wmmSBffKKfUQ2UBg+c/fCJ0CFSiAlE73LSdopx8=,iv:eNzCRC21OF04PUlOSf6WQrfAeMJnwF2jdZqSA5GPgL8=,tag:YkRTBnDotJTy1d2HVulh2w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:PMaCMDo3R/SX+6txMlZsMoO5Tu9KtXOP4jNUrYOYCnb1ftii7eQ7FUV2ThVANDFXNEiXe7SFNNg+8cozh5orA01ma9gAAWS9+otUsjxBTGZ9HhKbLC8SYizhs/MUZoZ2vSTKZdPZTkGVEuYDaJCEr0su0Jnz5c3IC6aMrOGgjNlJIFTIs7e6CjJY+4B3jCv3uj4E0bhYlgrvn37Vf4IpCo546yc=,iv:oHZ32pElMR5oplOcLqLAJlB/m0n6BiGTk2aB0gH2b/M=,tag:FY+GTtgDWhFEwyWBAO4t0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dDlCcnNPVTJyN2owRjVZ
            VDRyOHlPL0F2Rml3bWRKZVZQeTB2cStTTEdBClBLSVg5NnNHeEVMUit2RU9qejdN
            STY1ZGtuVWNzTTlzWC9mQkN1ai9DT0kKLS0tIEk5ektRY2IzWmdFNmxzR3BsWE1Q
            TVJmL2lrQUlFWTFHUnRwNHFkUUJpbkEKcJGGRyPIUDIpcusvJGkpPNsmb2Mi6r1m
            H7qC4f865L+Ofn4Gd/BCjuhF0HFLNFA6ZiLIu1rQxncgPOMrGXA/8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T11:25:29Z"
    mac: ENC[AES256_GCM,data:m+6pSlCVrTuUygYrDe5HaBhcxjT/p1rnrtqDlzZdLuUN0A/UDYQM/UVnWTZur6Cfink6h8g1eTBs8DkpS0fWfX4sUvlRLQWVwQ4N4JaDAntJafTOapXJNCn095YQFJNjhfJ1g7wtCDb121+iJrsQ38zzv/K61BGuyodrkANXT+0=,iv:j8Lde9x+tWnvYKp0V97tNxeWXCkztgv+kHutmNNHg/s=,tag:+SbxFwIHvLXs2bMiSXNWMQ==,type:str]
    version: 3.13.2
