apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: svc-openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:kUOzkbDg3SgYvrRByO5a6fP38GDaXgpg1x3SJuYotefMxbKSndvo5LIkqHk=,iv:gALa7pvhzNvuXNUmYKRjQzPiD/V0A5NDVea/ABii8Tk=,tag:+8wyv7/5j/Marn4AqJ94DQ==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:cZBK5Y1MNOXlc9zhM4j0T7jpt+WergOlFw==,iv:7uYk2Ekit9lBImXF6YBadEJB1o3ODU+7mk5nrHulwWU=,tag:WaHUgRtoeqdn+B82x3xauQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTU44Q3dDQWxFTEtudjA2
            NjlNL1RjaGVGK1AzeUR2cmg2WkJwUmFKYnlzCk9YMWRKN0hCVUgvRGtKeWpQczBp
            MnU0RWNGeTVNZllFSzlONFFqbGNiZ2sKLS0tIDFTcVkrYVpHZW0vcVRhdStzMWRT
            R0w4UTBrZ3RTQzFFQVdFWUgyVHVlaG8KOikjpmtGEQymMvuq+7MSJEHvMvQzt34H
            JWY7imN2mHDfKjGXwTK2tTtuz7vV3k8iXeUgPboXtx4aLOrqzfPy6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T00:52:35Z"
    mac: ENC[AES256_GCM,data:OdREadP1XO2qW7VZrFfNaLgsb2aMx/BzhYfs0rApGro2P51eUZM5+jnNFQROEbQvde9XMK8MeaC3jV9PwNjwlIAkqyTbbGZ2y5FSBh3+jpHmMWwkS+SimkdXDksFc1nLpukkItk7PGUzAnt0pEuNzF7MgPy/b00ql4+Cru8i0GU=,iv:a1GKCvyHBNzkPY7eA7ulEvE433Oy+QaHAzNUxKR7lE8=,tag:w6e7dSdueDIM5NpdftMweA==,type:str]
    version: 3.13.3
