apiVersion: v1
kind: Secret
metadata:
    name: influxdb-init
    namespace: ops-monitoring
type: Opaque
stringData:
    DOCKER_INFLUXDB_INIT_MODE: ENC[AES256_GCM,data:GEpjZ7I=,iv:I2VucixF0gOLUGD9tA+fC0Kd6kwwOEQTnccXaumRHz4=,tag:Gjhix7RNSnmCMjXnBV90Mg==,type:str]
    DOCKER_INFLUXDB_INIT_USERNAME: ENC[AES256_GCM,data:zun/TA==,iv:ND7USEhTA6W9H0GIwtPsN5saGyhlC3zUReVg71i9Baw=,tag:ybKXCNhmA6NKnjMNFCoaUQ==,type:str]
    DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:X+PsgdeYuPN39g==,iv:Cg/SwjIpM3N8LjQwCDWA/hvlHt2vDvd/jhM/vcQ4YzM=,tag:yTL/vlvLj7zlof86ihYDow==,type:str]
    DOCKER_INFLUXDB_INIT_ORG: ENC[AES256_GCM,data:+hTnsBMY0w==,iv:8HD65PIabwMfaYm34TIaiFK1jWjfaL3xpVd+6+QrdZw=,tag:1gR3DBW1/208kEoddX1Y6A==,type:str]
    DOCKER_INFLUXDB_INIT_BUCKET: ENC[AES256_GCM,data:Ms3uxlql/Q==,iv:yaVoqP+HgUwRzQbV5S01vS07YXWxTB4FxSGY0Quuvb8=,tag:/Fpbj12X6SUp2wVZolyzGg==,type:str]
    DOCKER_INFLUXDB_INIT_RETENTION: ENC[AES256_GCM,data:KA==,iv:S1wT1lE4q6FD4IH3gFQ5OKWPC4E+jLBY6Hj1Q8rt/WQ=,tag:twHGvt5Bc/gaMb/3zKaTdw==,type:str]
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:/2WlRudFN/5IRZR9IZPh/K5d95yD12ijDH6Q/bwjQ66HUyzYqcSREGQDy1QpRekJ2C9cFjDQZqq0mYVGRjxFgA==,iv:0bNi8NLCwoS60FrSy1OMZKTdHyn0nf5ATg43zjkG3hY=,tag:/nO5EkQG/ntQdiiWFH74aA==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUGNYbGNFZ2NtM2FqUmp0
            aWo1cDVCYVJYcnNReCs3aTBzSHdSMkN5ZUJjClFIR1hWZis0V2tFcWFwMC9kWktF
            MEdTamx5b3h6aEQvcld3MHMwKzNNUlEKLS0tIFNrVWlZMWdjb0Fuem1yUHhxSmdh
            QXByaU5KOG90R1g4cnkvMVdoY1A1UDQKm08VWysg6VTS3vr83ZuoLTdcEYWieVte
            6nAX+2lBEvujKoMU3X2IWTh0MelN86oAPuXZgtv3e+Ry+5Zslvef2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:45:57Z"
    mac: ENC[AES256_GCM,data:IREo+DGAgk8CLjIXWPq0IjLFNDjfuHiu43SRCsbOITtuu0DnwXz/VyVxzOdvGaXY9Or4oUZUnZreBfzhV+VW80sBd1tVGLUTevmtnJetpEV1eMXM3ld3xJDMTiKZuVnlCsZJfsNyXtXEb8WL2z3eAgba8TUml6OfSqJEYMDFONY=,iv:dF4g9JYmArP0hvMr9TyRtPLnwQizWg6vhUbuXeCxyhU=,tag:5I9+rkDAVj3Fl9TtrllB9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
