apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: svc-immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:9ahC5mmNMwBXMwimLoVH0ueIYVuVmBnguufF9nfA/lM=,iv:fHjNUIHev/uFW93A3GN41VPY+nL3oNxFCSNztrbSpFQ=,tag:EnzfVNEvhB4CER5RINe/Ag==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUm1LVkNVK1d6Tm1XbDdJ
            Tm4yOW45NFVzbStKMW02aWx3RVJJK0xHTm5FCjBTczFDMGlYNm9mWGxLMnZRSjND
            YWQwb0xtZlpBZTZjVlowMjZDeDMreW8KLS0tICtWODdtblhYS1FaZm55dFE0dlpn
            ODBkMitrV2xEbmZnYUwzSkJNNVlTTlUKIbXnd/ZaaU5Ul888SkxM4e8KfxNjEYXK
            DvvKgW1zkEpkv2EnEIV1GJNpWClsPK2YA8CGf1BEDkQYu1xBGfipXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T19:18:39Z"
    mac: ENC[AES256_GCM,data:CuSo1q5Q/B9zEXb1gME8m8V2z+OI75wSo3QF8in6iyjgqQ6NHqk2C0O2f8XAJtxwUHQcai31fbFTrrv8juq6e7lHV38/jtuAYZnwdiwWcwZrrVsoLjGtAgATzamr0O/NAplLBil7QqMeWhvgFOOIMAHQD8iVfSeG1PbAGgslVeA=,iv:20iFMBf4mbvs7aLoQEiModlKau/XyteAIY8q0KxcTlM=,tag:zUkFiDOtyS0+rqfFC3KtNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
