apiVersion: v1
kind: Secret
metadata:
    name: pelican-secret
    namespace: svc-games
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:vTxhepMXSr1f5G6WG2XRUQI8pw3CIw3bPy3Pt8TgSBs=,iv:bFp9YAVLqODBdnOTX2hC9lHIKxctAlcASXXDD3ZHEZY=,tag:VDfqu27cLBgg2v50RzTEFg==,type:str]
    #ENC[AES256_GCM,data:BF1mWo1xHug7f7tv14Mn76fhjGMsmM828oum6fZJxuaVLrM6/76UhLoSj6z3gG0UWlrGbNifUsnQKv0R6E6N8K3LSiGlBYJ7H/DsKHM=,iv:GzwWjZ28vDhDKUMFrQGe0JeAqSFbvJPMMzUjPJiBYhM=,tag:7ZnCv+NFkTlGWahzVzJX8Q==,type:comment]
    LE_EMAIL: ENC[AES256_GCM,data:7f38MFEDr5tzyYMNjgDGXdsr0+1x1A==,iv:Wac5O9QSVj8MfCgYgRi9jOhv8nXE2ChJjIIN/m/RqEw=,tag:BslaxaEiR22QgZSr0uovUQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQnk3RVQxZWl5Vm1CeGRB
            UTI1Nk1PYWFhSnlKK2RycDltakR4ekE0eWtzCjFmeTBPSUZxSXJGMHh4bjR5Z2tl
            VDhqcThBUG8wWnlVQVFuSnBHbGNUeDQKLS0tIGJjY0R4ellVZTk4clpVZkxLM1Y1
            ekNLdE4xaURJaVNpYjgrRWplWU5yVmsKa1lwjftr9T8x52/k/rwvZEr84kvj8UWD
            27tx146cH4MklzH95kz6MQskq/gCFxPMj7+vhO6R1qrsTbIk4QvYGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T22:57:25Z"
    mac: ENC[AES256_GCM,data:CIFuDFg8BtzOh9z0PGKoa5Sp6mP8jtlKBtZhAnUkvFfMIJfaw8w4QIqwcj5emxwi2HUoiT1o2NzeSzuPPuM5xQRLs76lGqM+xK1a/lFkeF+u7FyQgTbPfyaryGKOYh4ft+ZOZHcY4XopNx/5xoi9YptsAaiifRcVPrqplYurDsk=,iv:PsGBd7wCQnQqo2+K7jblrnp6WOVlpEtYxh4vH18gzR4=,tag:Bs3pyYt5UMvLppkxG6xvWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
