apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-data
  namespace: svc-games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-2r-immediate
