apiVersion: v1
kind: Secret
metadata:
    name: ghcr-cred
    namespace: svc-kochen
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fbgoWbLXePiEvn0OvcDmNwZxxa1H0lHtATgDLHg1jrV5yJrm0DusPqW8UE5I3X8mUJKbCvfkjgyIgcsETP+X/S4r3JeYU1hXfqrUknpXUmaC0U7DxjLizfdCFJCt0xzZaPHz7YAUhbEAFsSwGOcgd9TyrAaSuur0C7wJcI5OujizX65moYWLDNfRw9qvxxHVZ5kBGQN+CFoYskBHjUGha7ccN9jWOWTvXAVEQkGtP7tMOSmaBm7LQ/kdxOOOSWMZozlAtHAMGMoy4Xc1DrI2+Le3o/T3qq0nd9aua6LL0IqPP3OKfe0giHZIiAjpFa4lC5oxOAumNJrU1IKmmX+WJl6gNOfmCxKnf2B2AGs=,iv:xuqQK2YrHD7ByaOnk1URpZ8MniOap2T9JJ3FugQDABI=,tag:YlZPs6tseLJaWsr+rc1cWQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS2oyVFl5YitLTnIyam5K
            Z3hDUFBzOFlVNE5wTEhXa2VqSlBkejR3MEdVCktCdHFXNnhHc1NXeWZNaXlDQnlZ
            ZmJsSXMyVWFjNVEybDR2MWNmaE15T28KLS0tIFQ3VDA0U0xudG5rRHkzWnFQYkNw
            T1loT2JlVW92NTNYRkpCd1UwdUdET28KtiST2Gns3IW0di8gKp5TpO+TS+bZbQ+j
            cJ45IczZAWobtbsrQOUWhb39YbAedt8lZGhshvzvrS2qoDKaHJX5Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T19:33:27Z"
    mac: ENC[AES256_GCM,data:tIE3pdHinhOFjecVvrf+MQ92gsA3QvvAeaYAGlEIxM6z2BRhsQVZWA2Dyz6qUa3cPA+xDDKfC65exbThqTdekjjLdJ5DfQHV6V4v7ox7sCxtNqHRgcW2ubVlxylMhlmiV3LUYDTc5ytRZyUsEbtuiBbV4ZpFHw2RFm4Wr/ERzoU=,iv:fOUk9MvjiuUSmpaNcmj77AwPwJ3fxojGOnHHYhGxAg8=,tag:D8eaYkmNzsKajubxf2iBeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
