apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: vllm
spec:
  target:
    service: vllm
    port: 8000
  rules:
    - hosts:
        - vllm-proxy
        - vllm-proxy.svc-llm.svc.cluster.local
  scalingMetric:
    concurrency:
      targetValue: 1
  timeouts:
    readiness: 5m
    request: 1h
    responseHeader: 1h
