apiVersion: v1
kind: Service
metadata:
  name: vllm-proxy
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: activator
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - name: http
      port: 8080
      protocol: TCP
