creation_rules:
  - path_regex: '(apps|infrastructure|monitoring)/.*/(secret|secrets|.*-secret)\.ya?ml'
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39

