apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-network
  namespace: unifi-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-network
  template:
    metadata:
      labels:
        app: unifi-network
    spec:
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
            - name: MONGO_HOST
              value: unifi-mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: unifi
            - name: MONGO_AUTHSOURCE
              value: admin
          envFrom:
            - secretRef:
                name: unifi-secrets
          volumeMounts:
            - mountPath: /config
              name: unifi-config
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config