apiVersion: v1
kind: Secret
metadata:
    name: unifi-secrets
    namespace: unifi-network
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:zgcA3A==,iv:sN3MVXuQPof1lUq9PrJcTuvV/8sIFtaRUA8qhh19ahE=,tag:rQE0CdyZJcSJQ82YcODrMA==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:Q7j/EVTKtVgpj97e11pWNA==,iv:oZmi3FtsgoTHI8aUNVDjuWNMhHSLoZH89Qe8Ipd+0dk=,tag:uMrGhaoOpgsJSs69CYjyFw==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:VxFXrI8=,iv:OXadZp1iryphm0fr+WkbwhnTQ36bMbKmFHVvuW+kXc8=,tag:BPUOvw7rFREpxyshM7aeaw==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:LT1sKNMOkyhwgYExKidj3Q==,iv:xtQHHlQuDsWLh9+paICu8LEogB98UTg2HfQccNW5ifk=,tag:BAe/NBMTYVgX6PozTo1XOA==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQjdWU2RjKzNIWGUzRkVD
            VEZzMnVlaVc5eFdJbTkzWGY0SUUrNEZienpBCjBVT1BmSXBLT1JzWngvQ1pyU1N3
            R0w5UFlJeDRqc1FUaXdMSWcwTzVIak0KLS0tIGRzdzViZkVLU3dUa1MxNlE1UHhB
            LzR4ZktGMzlhc0J4ajA5WXhKc1VGQ2cKPgZoTBTNTHGWrlPmNtKBE9Ci7GsG/m4o
            uNqlrNGkfLhXga+XET5ZIz7V2xJkQ/SQ5aav8rtt0izw32WgWcQQhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T15:55:56Z"
    mac: ENC[AES256_GCM,data:Wml0W6Zf/FbF4zXdctEK/IymrHhPCe01aIbyNY8RThksb4MBW6jJJvkKM3Z+rG0LhEPjbOAbUOqqINGw713DkVRSiVaE2Wipr6dnoJULltXHYRB1HrOqcP7a0PnWoWO9YZddRNK8hTBqM+JelFvl7mHRo867wunfAYmnpRcQNl8=,iv:YqM/jyFs8H63Z64Z7UBc+azNb1q30yFRO669kYwvOyM=,tag:5Ao9yzcWC250njny3caf1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
