apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: frontend
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 20Gi
