apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - open-webui-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - postgresql-deployment.yaml
  - data-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
