apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TsEJYBF9aQmN8nqBsr1S71oxyHu5UVkIM7K0oUla2HDuBt4E4aTpHWuzy/LUulI+5EK59h/eTyg=,iv:xFS9zf8xHqRQ4npfzrhGplK8V5t7cS7roMYVH0l51cI=,tag:X08LaZHTCIAjKNGqVUzoKQ==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:rfTqCVFHK3lGAa1EuVL4b6BcJlH8rMewjS6qtdREISNPnM1OXAW99AaNHaGgwVqU7Q==,iv:AbDVREeH0dG4IPVL2s6EG1UbqZaaK+EJmagbMTMXjrU=,tag:+XqxzeM2JzCBUEkeyTycRQ==,type:str]
    #ENC[AES256_GCM,data:cVErMKoP/UEagrFUWWBxBsl3qWdL9NKcZUBN4KzK0c1D5m2eG9nhdolkB6B/L8GbYiGJVsvVQPunBA==,iv:0MQroga3KXcTCuocJZk2imRp8PMtjJgG4QE46ck2q8U=,tag:2i/+WDlyhIohl/ogqP6jRw==,type:comment]
    #ENC[AES256_GCM,data:GsDF+Sj6mCsXixPfDNl/W/XPEyLv5OQ=,iv:BUNm11ya1MTg1BRoG7RF+x9+J2BA0UCg6kEHZ2Ih1Hk=,tag:DAa6koRaEH/JMkfL4BraTQ==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:jCGCoSCeOLbUawV+rEh4oeu8U7SLv+WLsecCoFPDzrjrGMIRJBtU2UCqJskYgrnoCmpFL1FiA74f4onNpai2sg==,iv:vhKnIrai+57LWGRsCj5Z7um1mGLOn1Mw3UKkxRkzp4w=,tag:t/K/wLebmYeSXlNwnlYpWg==,type:str]
    #ENC[AES256_GCM,data:omMKN/WPQkcfawhcXs1/aNFol0uufKVNLeY6pyAsruxS7qPngDlBj0/wsasYYijzuXEBSzSZxYeXwxNyW7iaVqJJAQGJ4Lf2jA==,iv:4QFr45x0UgtHH4b6hVBuv8008bHgCjWnctDNUnZ04xM=,tag:eCROPO3S5W0I4Fm+4daZAg==,type:comment]
    WEBUI_ADMIN_EMAIL: ENC[AES256_GCM,data:jlpwuiKRxORPsClN/3qH9V9nb4Qgow==,iv:ueZJzPU7MUy0ZaWCjoPLHxGR4N103h2NpIXfD39vKKc=,tag:qkJFA79rWP3eHriIHz1txA==,type:str]
    WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:kJBuK87HwAGo+dzlJf96Tz6CbMkCTFxb8jtC+O4gOPMwdQ5tIJZ6uQ34B+T3DevUa9ggC6SNwDrBNP/OdLz+ng==,iv:1V2SWMXO+p45hOCVRgkBg0ZnKHm8S6DgCKozx+3kYWI=,tag:rqo3uiGIrWAZs5F8+lWyPA==,type:str]
    #ENC[AES256_GCM,data:zdPjDLGtsFbD42c/RWsZKvSFicC8sbXT35T/QocXhlJOItiDxS33U/Tns8VY,iv:qBESNVYd7l7FqUsGuNPP8WNFkIqQw6H4sfjlP8pFChA=,tag:0FzWF7KoKolOt1gzH0OlNg==,type:comment]
    #ENC[AES256_GCM,data:S6ZF10GZvDOvpYmFq9gx4zGH+dJbZFw=,iv:KgL/8LER+p2QMynl/agwwNvROKaf0lA1B33nvblvtqk=,tag:5haRKV8vXWtiilg2CjEYUQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uzAtvmYJGSN1Zjnu228lifOmaGZ5L/+/5U3Poteut98kZ/+EuaZsWrH5tYH9lS/DNB/z63iNesNSxHwDOMgzIA==,iv:kmYT6Ou3rhAShLZCEEuLgcvFk97GkcESrOsPg06FH2Q=,tag:4MOKxtkZC4hAtYfZzyuEzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVnNqS3dITmtMVzZhMkJK
            ckh3YitDZXFKbDFOb2k2emJxMGJpVW9PVFdjClNidlhpdmZWbnErWW5MRmxKa0Fy
            b3pJRklablIzbXBNKy9lVHhWZnRiaFEKLS0tIDl6WndFQ1MvNG1zempHMGp2T0E2
            bTdSZ2F3U2VqTVRNZTlGTHVkUmNrT2sKKkTGnuNdHlQUIv/n1pKvTD9VwGuQo/VS
            Cltk3QWgPdg3jhAiv8hzZvWfTN2o7VNkz/zpD7ZExsdJzIF/+GgzuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T22:50:06Z"
    mac: ENC[AES256_GCM,data:jYLs4uz1IUeBkxZYfcUmRDporrGL2GEzN0M0ZTgke93QdMqv61PjoLQGA55Fub+umNzgJcThbzQ+KwfNU3lO9f7CJfiu0gEkXVQO+CMTBEIloBumS6x4UQVag9cdnKScTC//RZ17iyoYX31kbCXs3M0hTQ5zQzA1ym24DytTpwI=,iv:uK9z2c6Hv+YQqJ9/5bwV72+qjVZZ4HvSAvUckmkrE9s=,tag:Bnn7jy3Qc9SG0+RygbM3GA==,type:str]
    version: 3.13.3
