apiVersion: v1
kind: Service
metadata:
  name: embeddings
  labels:
    app.kubernetes.io/name: embeddings
    app.kubernetes.io/component: inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: embeddings
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9000
      targetPort: metrics
      protocol: TCP
