apiVersion: v1
kind: Secret
metadata:
    name: bifrost-secrets
    namespace: svc-llm
type: Opaque
stringData:
    BIFROST_ADMIN_USERNAME: ENC[AES256_GCM,data:Dy5mXo0=,iv:81gOkHyS23QnMiAz5X5L9O0Eax3grqj13XstrVsSZO4=,tag:bHYaUfoTVuKWGhFzE0l4WA==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:WsZFcZJoVZ3tXm7t+dku9/wer7aegBq2qDNyQDMXvLtVZn+XAipbdlqf+FN3qDVmajN88CLsY6nREXCnWd4VjA==,iv:1+svcN75N7kA6BmElSgClFJgaaNpP1zYBSjaYYqBv8k=,tag:wSuTTJZc7/7yqUzX2efmFQ==,type:str]
    BIFROST_VK_EVAL: ENC[AES256_GCM,data:JjtnEjLMocFgxM0u+PqUUndM3YGsDLXELA4kZBozXxAhnX3lbXSC4ffDZu7knq+BhLTYIMLF5nqVw7/069DI1DroTEEivg==,iv:BtZ3qVv6uNPTfpfH4Z7P8QQ8PoDfL9Np4hFyjRzxGMo=,tag:qnGv8SfTB1yZIdd4FFRf2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTFY5UW5HNFArR1F5U3d1
            eERTOE4ydERUcHI4M1FaMHkrb0RzRUZPR2pjCjFjL0FXSUMzb2JDT2tnMFJtM3R1
            R0RmK2JpUDU1VStBR2hoMUVvb2ZSUTgKLS0tIC9hYmxoemVsSTZkaGJMeDV6Q2VD
            c0hrREdFZlpMMjF5SGtYWGdoVzlIaTQKrgtgj/zV3RA/FFmX07UK9jvRm2tCTuiV
            PrduEJZf4h/SXfa8gOIlEUkZGg/e7EMmNz3MpfQR1xNEbLWygnVnuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T16:18:59Z"
    mac: ENC[AES256_GCM,data:GPWXsoVtygCqsjhoKzNuzOw+wj91ymFE8CYeZ2EEf6580AWVj4ac1IihyzOiHv+ISrsitMfxbJdZeUdgDK055EeGUjHju9WZKa2nZNU7lI4da/T1ZmpiruGFOkJppf57U0gFi/WskJi41+R8pzT8yVPoFKSdlUPVJH9K+QMEnHw=,iv:JfelppatYQAhg7EV+ihOQFCFlZq4ZtYm69upIwMzI8I=,tag:Gn8q/Dgem9bCgfL0gZ+jTw==,type:str]
    version: 3.13.3
