apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: bifrost.intern.rohrbom.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bifrost
                port:
                  number: 8080
  tls:
    - hosts:
        - bifrost.intern.rohrbom.be
      secretName: bifrost-tls
