apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bifrost-logs
  labels:
    app.kubernetes.io/name: bifrost
    app.kubernetes.io/component: gateway
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 5Gi
