apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svc-llm
labels:
  - pairs:
      stack: llm
      gitops: flux
resources:
  - namespace.yaml
  - storage/
  - vllm/
  - litellm/
  - open-webui/
