apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ops-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.ops-monitoring.svc:9090
        access: proxy
        isDefault: true
        editable: false