apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ops-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.ops-monitoring.svc:9090
        access: proxy
        isDefault: true
        editable: false
      - name: InfluxDB
        type: influxdb
        url: http://influxdb.ops-monitoring.svc:8086
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          organization: ${INFLUXDB_ORG}
          defaultBucket: default
          version: Flux
          httpMode: GET
        secureJsonData:
          token: ${INFLUXDB_ADMIN_TOKEN}