apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: ops-monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:CA9K1Q==,iv:4sfGCa2OWPHw7Oygy2V58gp7SveegGiKvTJ1rlKfD9U=,tag:YosazdmZ+ILNKoX2loMV+w==,type:str]
    admin-password: ENC[AES256_GCM,data:xMLk954merKoMg==,iv:HPkqIqrPTZwYHkKp9IVzCHQ35ofo5SNg1KCkKTflWPQ=,tag:LnektV/eeL0ju8BVxqNYqQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTWJIOGlJd0ZLM0lzM0NZ
            cUtjM3ArbE5GTEJka2ZEVjNRbjVXU1duOUUwCkduSXcrVWhhWnhDNzJRU1FyQlBp
            RTBRK1BsdDJKTENKUndXek5QUEpIbTQKLS0tIHJXdmp5WjNVQmk3OXd5VFB6Wm9K
            N3VJWE03VjJGWTEyZlFaQS9vNzhBQ1EKjoxwunZlfJJj+JhDKJ4Ga5oHIJGxRcex
            t9k1aiYIsM0bwMFA3npBh0sklpWbunFO19/2s9AuhGVdOPGESjHroQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:41:39Z"
    mac: ENC[AES256_GCM,data:PKgHzg121b787HriJ9H7RyHFp0rDEFk2+Nn0yypvMH1FvkFUe+oxRoYjPvDKKvLwo6aFoGpn4IkgBj1dIiIHnwhztKCS6AUott4Pa+Lzk+89j5QdXLHq3o8nYrf0gztCqybrGQLr6gMHVHYRDq3slyLe+gnMKU0sBM/+KJWQob4=,iv:6GiE5P3k8Wi/1pXGO4bnhvuNV/nNQDJ8i3j6/wzUKSw=,tag:gfcZi2wKP1sKPh7stnAHfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
