apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-secret.yaml
  - pvc.yaml
  - datasources.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - netpol-ingress.yaml