apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: ops-monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 10Gi