apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  template:
    spec:
      dnsPolicy: Default
      dnsConfig:
        nameservers:
        - "1.1.1.1"
        - "1.0.0.1"
        searches: []
        options:
        - name: ndots
          value: "5"
      containers: []