apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-main
  namespace: monitoring
data:
  telegraf.conf: |
    # --- Agent ---
    [agent]
      interval = "10s"
      omit_hostname = true
      round_interval = true
      flush_interval = "10s"
      flush_jitter = "0s"
      snmp_translator = "gosmi"
    # --- Output: InfluxDB v2 (Bucket: network) ---
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb:8086"]
      token = "${INFLUXDB_NETWORK}"
      organization = "homelab"
      bucket = "network"
      # Nur Punkte mit domain=network schreiben:
      tagpass = { domain = ["network"] }
    # --- Output: InfluxDB v2 (Bucket: server) ---
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb:8086"]
      token = "${INFLUXDB_SERVER}"
      organization = "homelab"
      bucket = "server"
      tagpass = { domain = ["server"] }
    # --- Output: InfluxDB v2 (Bucket: cluster) ---
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb:8086"]
      token = "${INFLUXDB_CLUSTER}"
      organization = "homelab"
      bucket = "cluster"
      tagpass = { domain = ["cluster"] }