apiVersion: v1
kind: Secret
metadata:
    name: ghcr-cred
    namespace: ops-monitoring
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fWEbAvF7BwGCJ+lvDsoJbrUgVPonHWTOWknyZBPJGLlMWgXKwFIH4g/IzjS+1W/iAAj06wgSrE/svN/dgZSwgbnE89XvbJC88qkOWJzJzE8QZ06bINTAVuV4/eHOLJRB1ttNJLsv/HxiM75yEHistp0qaQ5iglXSP7I2erIcv2N4Gmvw9WPlRjqGzQXjMJt1J88Gi0WYm4CDLadsPllbMNDPXh1DTnNsLtOiuPTDbY5zTX+VM29rtOsIh0s/sxk3mRhrnEfmwu+eJMNGlj8DLxoPH25Yxqn62nYyeGa84PzlIW2r1V/w14KEB+m8VV8jAbVkufquX/bbZnXTHZtNiyfWnOqCZrHvSaZ/zaU=,iv:FAuyEqP5ChOO0SnvyO/iWE47RZM4S+BevgHR0N/NSsk=,tag:doktL4XCuf16CHo8i3nvUQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUjZZQVJzOTFVc1c1aVcw
            bjF0NXcvbktiMnFrQkZrNHVWMWtxOFNIdTNnClhhY2MwRWpONy9rWEMrQzFvcTBh
            d2dZUnNIMnQ1SnVKYUF1OFd6OXFUUHcKLS0tIE5RZXFMSUhCQjF6MFowL20rSS94
            dnJDeVBjeldYbnJnOGhNL1dDUm5WM0kK8Ts/vot3yPfDb2Eg0JMFiebgVRvibwCO
            TmHTVvZ8dIpIp/dr4ZoMT7RIY1n4yTX77i5J1CbkYRhHvm02OwSNQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:14:03Z"
    mac: ENC[AES256_GCM,data:Fu7IjYs91x5pemTjPgTF4+u8pT0TLmXRkYmMYg2G/Eugg5lx6OsQ5tor5UXbL8Fv2YVdRO38ZET1IGk0DkKKfyQezV3jsLI8ujyImFOd2k8gzGkJVIjxt08yDt37TN6HVzPMYAcVVZ6eX3u41NatviL1hIx3g6/zLsA0kFc3f3Y=,iv:+4IBXGigO09xlCNAkhFZpAx2Psp9MLe/eHnO5F+hXlk=,tag:/z2ELHSfEuIoCzAgv5UfQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
