apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secret
    namespace: ops-monitoring
type: Opaque
stringData:
    IPMI_USERNAME: ENC[AES256_GCM,data:iJ1htuz1Y0m06YRpAw==,iv:ohubMc1uNnW39YNe650x3RnQFyf2pa/ExBfix+HN2Y4=,tag:QzEzDmWVLhznOGd/16spBQ==,type:str]
    IPMI_PASSWORD: ENC[AES256_GCM,data:RXHOv2TDj5U3OtWWH44iHzSBV3c=,iv:zjz8x9O2fWfoWl2wdnsrjg/hB/zQYDnyDmxUyXdhqwA=,tag:S0nDQ54avjwCYze6oS/wzg==,type:str]
    INFLUXDB_NETWORK: ENC[AES256_GCM,data:PqubOTvyoyLA6hN8pWSRxz73fvzlO0Z5XhacplRjsVUcNvSRwJ+1D7xZKR94/KpN+rB9UqVEM+OdD0aFEFrdKw==,iv:fOWvAL9JGtLNLt8oBHlpBaRVpnpgtOMLCLR9ISkoOHw=,tag:L59OI38I7wpzvSMuziAYJg==,type:str]
    INFLUXDB_SERVER: ENC[AES256_GCM,data:it+v7BPg5DntfHq/Z7Go/1HUKb0bjCiPhRaZciKuPnoMAC77pbxdOac57u13g+ciEHAgN3NobGG54z1hapgUbQ==,iv:Hmd+2KZLh9jPBTgb9lOf0w8NAAdo1gUmj2qyvFPMeS4=,tag:rJ4UBMKLWB51VgpJL/+fsw==,type:str]
    INFLUXDB_CLUSTER: ENC[AES256_GCM,data:Byx6q6xELuJYmax5eWGOaJM7YyemE0l3v6f6cUYtyrm8a/2JtfrUlPDsrG5bu9woyKDWSYHokag/NplyqvgfqA==,iv:XepYx8RHUK1VprBnFO79USaUXHFHW5fn0r7Aw9wvTHg=,tag:0bbM2wArLEY0wdHH5VW5DQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNjd5RCtzRVptdUkyak81
            RTVOeFcvMlZkRVhFREdaOVNxSzBrakIyY3lBCk1ES1hXRWs0SWNTZC9aQ0I3WUcy
            TzREZW1kUG5oS0FMYkVWaTdFbUJNcXcKLS0tIHdtYUgyUW00QTlHdjlQWTVWQUc2
            N2E5U0cxL2Z5SXh5cE5YRXh4Ykp2QkkK5+N4cHkn7Q/05OjKYnjHCSx6pPfPAtO+
            RVDWSNSCwBM4waewBVPbr03ITXVOCMRSAo3vMfQ6WH+38CKGGZU0qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:17:49Z"
    mac: ENC[AES256_GCM,data:GxldF3rJ6LIjQeJC1qXUN8rfE7hPYP7arlBmGFDRoCC5Eyadp9YqJMAq4XG2iFIeGL32mthcff48XdaoDQIu5HBfJRAbaSNkyaeY+w+gUekZrx2/EnZIeOhSdM8pu9xrg4zkCsU4AGK6jo7UBc4tvX/nx6Scn/BcH8ioYnzIKH8=,iv:y8FxjoHFkJOjAs0jM+YHn8xiklQWlq8FicxFIzRY8pg=,tag:qP9+M/OOjI0MAH95JsIaYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
