apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-storage
  labels:
    app.kubernetes.io/part-of: llm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: llm-local
  local:
    path: /var/lib/llm
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - wk-5
