apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-storage
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: llm-local
  volumeName: llm-storage
  resources:
    requests:
      storage: 500Gi
