apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: svc-linkding
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 2Gi