apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:XfH4we8B8/vuIb/CKLBnhUTvnGpHxP5pCCT4KDV8nQzo0Dpi0MpKB6hdzICi18fNXL304stPcMEGSF+N6+2iMIkr9Q==,iv:/COnnpPOJQb+/tj+yupd+vRGxcZozxKRLycAfnO9OE0=,tag:iA6uj6W7uvueXBFyi0krxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT3lDU2pPazZ4QjYwQmRH
            eUlmSnYzSlA3RGdCdTFtZlZJT0xGWHA4TWtZCmRlMmI5YzBqTlY0dXhqR1gwcG9B
            WlBhV3VMTkJNOTc0dkJJZlZ1NXNaRTAKLS0tIFZSNmx6L3hOcEhZczQ1eGQ3clhi
            M2pJUlI5TTNRK1ZyT0kzTkRuRlFZWFEKYIXCzd20P3SzwxCFPbO59wq/5tdAzQY6
            az360bn/DLK8yX9xXOwhtEnP+oYlZAacEIumTSx/eysBi7Av4IAxRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T22:19:14Z"
    mac: ENC[AES256_GCM,data:gIYSh4pparjCT7LZFhQpJkLjsQW6PzwLsn6DYIvD9oPrufyDOl5fg/WfM0lOaYY/gjAA/RCPbQf96PK/P01Ytifmx23u9/g1j2bIwuPsTicJWO8lFrNjrzzRHuDGSUUzHvPPR0EojCe+uO92pdcPmQ80tUngSa/naJcA/7RBoQQ=,iv:LlX579qHnmO0CKPDf8lVE778SREJJJL/D0biZTzHq8U=,tag:NvMk1o0hEQxrhtWrCd8eZg==,type:str]
    version: 3.13.3
