apiVersion: v1
kind: Secret
metadata:
    name: litellm-database-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/eG4K0D3ZnuO//6/nDFk/dwEyD7jlXMh4CBQymlvSbS8K83rUEMWRqRG/4vNk2Y9jZU6ulW6OFNlmdN9g3kr6cSq78vuYwuj,iv:fYQqr3cgzFJkT+nrVZbI35yi5Q9ZYxjRg431xAf+7ro=,tag:2YsWnwr0nnGi+RMSHN9V7A==,type:comment]
    #ENC[AES256_GCM,data:DhiRGgBupGuG3OhssJAqLTqyEM81B5ASu0Gp/6Yfp5kCENZZBYPwmfFJfAfZMGl+3fhE,iv:4LbEcAgch7cJ4aEwBoJ6h96mRKIvdzao382L90FiSF4=,tag:WHJZurpennkG+GIC7DNmNg==,type:comment]
    #ENC[AES256_GCM,data:ZEFIE1CgftSr1gMvXHRaJYreOvfRHTJXFj/bG0quiooSQ9o7r1SUVA==,iv:3FogGif3JTUkODxUyCdlPV11R2NO2BkBIGfHUeIN6u4=,tag:pUQNCwgybuPYcat/PXEGYA==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8OvJK8h9YH+A0tFj501Z55Ynm5xuRn/xZ68ZgIiKoSwuZBsf2aDKy5jfQ9dZcBrCeeL7lEWGGAE3v9u9+hwKEg==,iv:nospgAWeWp8qzY+S2V5z4j3sN6K6hwpvH3wTDXEOZJo=,tag:3z2ggMaZvS865lwUOTQBtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YlJWeitoN2RTeXBObnFl
            ZE1tYW5sQ3FIaHpCMGRGRlUwdGE3amJhMTE0CjMzYmRza3RmQzNweUFMNmhzZGhi
            L0NTQWVGckdOZno3UmtEREZTUmQ1TGsKLS0tIGpMSlcxM3dvTFFlNmlNdW43RE5S
            VHFKV3A4YzAvZU4vaEVoR0dGRGh3UmMK7CSCy3M5z3YcFR1q/JZLZPQ0mOs+rkOC
            WveNHDSV7fRW7R3BmfmPfnUPZygLIUjc8H0owS1P2InF7lCskaqHvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T22:31:10Z"
    mac: ENC[AES256_GCM,data:cukyl4dYFId6OWhjd47kSGJNrhTNj+/Pm2nxsXy6D9m5a1GbwomX/kGH1mntv1PvD+BqiKiT1OnQVhzcgARJsFRKaplIxbur1fHIlc4VU0TJojArSf8trwALQI3niXhKTfokxdk5HK82GoGPmkyzIDifdXSEK3ShsOW9GQQ2XwA=,iv:1tTk1T3sjX7lRZhC5jdWWsPLbJQ3bs5t9XX29ldFWEU=,tag:2GcEP+Z3xnvGJZHVtmWS8w==,type:str]
    version: 3.13.3
