apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:FqmAAYSITJraPCmkonORUi81TyyC7TfGMYIQA8hZWZh5MFlp/zifJ6gaxTFS+OnirvHeoZ4693sHcFlrWFBEN7mWaw==,iv:fS8OhK2gwHc91BDCYFaaY9qIINvv87gQEvzKE4wi3+o=,tag:U2RfJIShkAdqR8JwI32pRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVJXR1VjNFBUVnkvQmZV
            TmFQaFpyekUvOUxaTE9RbVRPaTdIYllmRkhVCk8rMUJrcUowR2JvVmd6ME5rNEJC
            Y2dEU0I5ZjBERU5PWW1yVFZONXZMOFUKLS0tIHJSQytrdFgwUjNUZDFVZ1VkLzFS
            dkdMSU9MRUJUSUlOclYvbVBvVnQyS3cKyND2x73D49d4vyH0CZOua1xWJRJ40KYu
            NtpHHCpW1CH12RLcQJYGZyw+ZHd1c6Yd1l/5bP97PEdk8LrrM+rj7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T01:04:09Z"
    mac: ENC[AES256_GCM,data:3wy0I+ze6Zd9w9sfrjzjnwI4d2D3bvehKdg39hI19teWXrSl07I91DP1OdGApShplnjaKNu5b6qQCXp3IV3TGnommkZ7ZaOgRT0HKeJl/Ybh//1coPChq26za71Virjak33EHvOu6wkWVmAKYfLdHUHtbH7NgToI1WIyI/65ogI=,iv:oMjU+jASXC4EetQxb6Oy809pnxHFGRJGtDLZ4mie8VE=,tag:DTUEBw1qzfj64RHOb5lv3w==,type:str]
    version: 3.13.3
