apiVersion: v1
kind: Service
metadata:
  name: litellm-postgresql
  labels:
    app.kubernetes.io/name: litellm-postgresql
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: litellm-postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
