apiVersion: v1
kind: Secret
metadata:
    name: trilium-mcp-secret
    namespace: svc-llm
type: Opaque
stringData:
    TRILIUM_MCP_TOKEN: ENC[AES256_GCM,data:whXKPpo7v02OJAAjg6845h63Q2l1o3qGoaqcGb+LSkYhEQD1QSbtWpzzVLmHygpXIZECxxqEIzG0,iv:2sZ98qcuyxXC71jYRmOqB5doW0EWZNfrA+gaPDLRvlo=,tag:88CO9CfFH/priQ2mu7DPJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMTVKTkhKS2xrZE9FSWlq
            MVoydnR4cGNkVXI5SDlRZGFJejNBWVloOWxVCmIybHhpOFlqMGVuOUtDclNvY0Ru
            bmR6RjlSZW5HNmlhbStzQVJZa0lsZFEKLS0tIGlKT1M4THJQVmVWZnRPelozeUlJ
            cGxsbmMwdjkvVStvekxmM0MrMmI3a3MKsT1FdmxVm7dsvU/4sNIVdpKKRaVPS2O4
            17NCkQb7pg7YC0U2rDlCg+krEeZisWHNmCZpLUSke7NUuB3ek/rkWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T22:15:25Z"
    mac: ENC[AES256_GCM,data:yf4lSiUH+qLhyk4VCE8/xcPbZiF1hJjhXNKY1VfQAAHNXopZmuNqTVEoSL0iHvRIFnA2GUuElIfdpRzDuLw7fZMWKKV1zIc8agDjx5dS9Uc9qRLCfL6wwfoBICwJKD0K4jLPTrOi5KYve6xr/LmyjPWJAqY/quU1SJRjo09C+xQ=,iv:G4fn0tRV2MLrowDZCLxEflEEj2qq3VP9IIK3utQncTA=,tag:A7ZiOAzbTiDcWOmfHFDgRg==,type:str]
    version: 3.13.3
