apiVersion: v1
kind: Service
metadata:
  name: pihole-1-temp
  namespace: svc-pihole
spec:
  type: NodePort
  selector:
    app: pihole
    statefulset.kubernetes.io/pod-name: pihole-1
  ports:
    - port: 80
      targetPort: http
      nodePort: 30001