apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-tls
  dnsNames:
    - test.rohrbom.be
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer