apiVersion: v1
kind: Pod
metadata:
  name: vw-loader
  namespace: svc-vaultwarden
  labels:
    app: vw-loader
spec:
  restartPolicy: Always
  containers:
    - name: loader
      image: alpine:3.20
      command: ["sh","-c","tail -f /dev/null"]
      volumeMounts:
        - name: data
          mountPath: /data
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: vaultwarden-data