apiVersion: v1
kind: Secret
metadata:
    name: media-backup-ntfy
    namespace: svc-media
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IXNHh2weNq7pOnsWycycVHgDX390AlQRLCDvW2oZbE4=,iv:3jCs2cYu7PH7AHXWkBtuRkNdnBgA++OgKD/mjfyH8ho=,tag:Wf4W3QB79ZusOmdIuL2J/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMmlJTHErTnFhV2J4ajcy
            M0JJRWtKWldIRkNha3JxVFFKSU9oOUdTdDJZCld5Skk5QTM4YWpUQkhJdllmZDBk
            eXlPTENEV3RuQkM0Nlg0L2N5cGZlRE0KLS0tIHgwU3hsblRRQmh5a250SHgwZDBX
            ZStMZUk1NmFmK2o3YUNzbHhaVlgvZGsKO+2e3OE9avKGdKo6eH19pfm/QeHCDWTT
            HgMjlBdr2n3JdzypoFW7YsdiU4C3kHDqCfqznM8iZOLC6Enpa0AI2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:29:03Z"
    mac: ENC[AES256_GCM,data:xm05mEhBweBt3nm9tdFvbArUEbIWwPxPy7Q7AMpDx4NnsCmgGJQdTGiLkZWHKqpmFYo7Ku8CQK4xFL4Mh3TgV4hUsaGPrA8HxJzTm+YddsXFL7/oEtApi3m8J6v3yFWFuwzQSQFDIcgODZQbIv8xJy3Xu/r4SZoeEUmfHpzHmzk=,iv:9THdJ1S6PA5h9h1TahYUsvoOcL4jP3M7JYydLeb6fv0=,tag:xBDrYItt4N8bEBE3yjcQhw==,type:str]
    version: 3.13.1
