apiVersion: v1
kind: Secret
metadata:
    name: jirafeau-secret
    namespace: svc-jirafeau
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:XAJiuW7vD/l1gVS7e8cTWriLzP1jA4K/4Rz4vLw0plv1j1Z8IlEHR7jwfWI=,iv:2pxsGuEXLkDWKvHCYpDQotzECgD/brhceMxi2TL9dOk=,tag:t4Fp0yseA1TerXsk3DkWHg==,type:str]
    UPLOAD_PASSWORD: ENC[AES256_GCM,data:Gb7bTVdbBpjFjL6a5zSDoi5/GOlrLZqcmllfFLwDkO9hBIWxkogDTjHuM5Q=,iv:XWQlePRNzcPlJhGFOft8VcvYt4RwIHeK+pcD2doh/Wc=,tag:lq3g25VtFV60fXB76v2z3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkVXV1g0NUhVRlNpamRr
            aFdIMUVpQSthSzhLeVkvVkJxc3VNSFFwaXdzCjFoU21pSnZYalhDdzlPN3dwY3Yx
            Q0ZSdnoxQUZOU0JVbmxyRnIvVVVGeTAKLS0tIFl4UU9DM0NqR2dwbXg3eGh2QXlO
            d2dyalZadkJFNkdodm5oRTIxRFpDNVkKlmkaJIkJT1b9s9A4IOprJlBpWSSzLJeV
            5jqEI8SjcrDAqZzcuuGyX/r3+m/8w0FXHnM12CWN6sLoypeDgURjtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T09:57:20Z"
    mac: ENC[AES256_GCM,data:rPDHt14azpZ5iCzwRbqzgdluTDvw28By8DixfToBs8/TEz2RmrH/qzA5Wg3/ozbDnHOOlaeUD2b/UQ6r0+8u2kqD6T0jmS6YyLw9Q0ULhG5wX5VAlrc1VVi+63TKBtVF50Sz7WfmQ2NUOhmWZk0WAOHZz3JCin9Fig8+tdc/C8o=,iv:Lo7KC125sfefVLX7QERn5WivQr31+1jEhl/VVdNFqKw=,tag:kcQbDnHqSYyDek26zldiPw==,type:str]
    version: 3.13.1
