apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./homepage/
  - ./stirling-pdf/
  - ./trilium/
  - ./linkding/
  - ./paperless-ngx/
  - ./media/
  - ./pelican/
  - ./image-compressor/
