apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wireguard
    namespace: svc-media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:l8sySGUqeV7NeeC834Bozc84sAXjqUuf/gTNmbqJp6VplbJmtd7WAKDS5JO0aSMcnrJ1gQDqoJ4sqCeSXShgIC3DOgFci5PtIncFbQdIyQ52jzRBv1QtbM1wTk89sjTtNkoTZeagHAObIsJ6xDX5eGn7Y2LOofnEeMIddDomoIfhY+U8xKKtBQ7xuu2HNerRUujvBrRNPdb5QpGTbMbjGOdVVQZiT8NtpsRH/zpHnbVzie9g9hK4EBCDTCS+vB0fXH4aBZjZXEViYlQ2syla7GtuoUS00yIoijQ5dMr3di2j5vZymdRdfxhU2rKqPZRqGjwe9vzOMX/L40ljOZ0=,iv:afR+6wTcIEOz0DYPjpHiBrutuVAumlWrNwcdbWh3zCQ=,tag:rIeMNdxllqbV9cAolaFt/w==,type:str]
    wg0-pre.sh: ENC[AES256_GCM,data:xCdG6glwkjCNRzH1irBYORmP7SoVk1bT3EuOO9aCuUnvrYH5FfKYllv/c5kHkH5GICFbuA5c6P7rqnyMNQh4d0btwSxnaZnYurhThGYpvWkWd39bjjh62PyyzSnBz4q8G6xWXEd8RyLgMKf28D3N4Fl/L9ZMHXx9n7M4y5+NYEvs6om1Sfkyc9ng26ymBVM6xh6VRDMDpwkBdsRSXKbwC8yTzu8IgwrU5m0=,iv:ZUQkwYIL3g/q5sNk9v8o2+HjUNt+K324PWthvmC0OUo=,tag:D6cnvDCZIUWOxUTYBVX/7w==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNm11Rk9SZFh0TFFkQ2dT
            SjdwdFV1TERCdEZFY3NTVFk0NGhORnpTQnkwCjFHU0dGby9kYlAyZ1YxWHVuU2JX
            QTJjNDk5TStPeG1PS29NbHhMMTNFM1UKLS0tIEVRNi9uamg3M1kxaGNINnY0RTlT
            ZzhvUzVBR1NPdmpjWllpVDF1Q0VHNGcKIKz1qsXmSWqLxG0eJFjeaeapH/3BAu6y
            4gb+itY5yX5QSBR07brdeIDlghaaykkZ+2I0uDwAq9ViqzlZNiZxSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T09:19:06Z"
    mac: ENC[AES256_GCM,data:rYRfuYXObDt1EmHVphbe7GhwkFizTsjwvtZY4mumfeb2PKvsI2mpDGCbJkkSiy87fMmi0OmDOQ1ATE3BppU4w7Gbvok25mV5T8aBZG7F8mmEAqTMU6PtKoId0ZbcuP7gM/662qdhxzoS/t9ZrgAz8koOobutGfSjft3C+Lm81UA=,iv:p0qVw3bDTVfCe0kqG+JRskBFkIejFg7cAzQfVQHugC8=,tag:lSgKMnLExKr2AghlcZDohw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
