apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpu-smi-exporter
  namespace: ops-monitoring
  labels:
    app: xpu-smi-exporter
    app.kubernetes.io/part-of: monitoring
    gitops: flux
spec:
  selector:
    matchLabels:
      app: xpu-smi-exporter
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: xpu-smi-exporter
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node.rohrbom.be/workload: llm
      tolerations:
        - key: dedicated
          operator: Equal
          value: llm
          effect: NoSchedule
      containers:
        - name: xpu-smi-exporter
          image: ghcr.io/intel/xpumanager/xpumd:v2.0.0-238
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/xpumd/config-example.yaml
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: true
            capabilities:
              drop: []
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: dri
              mountPath: /dev/dri
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
