apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-configs
  namespace: svc-stirling
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 1Gi
