apiVersion: v1
kind: Secret
metadata:
    name: ghcr-cred
    namespace: svc-mampftracker
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:p+rYKekwh/1BmNUV2CEWxz9hci0zlg7HmFLqycEw6sYY4qkfI8u2m4m2qjWQyZeYK7DGT8v8teyVMWLC3Xb57REUYZummItBG2+qr5jXPA3GdozahBgxMei/sYymAKF+XcEex0qcb9Y7DLaRPXvmmv8YQNQSX+MnfT0Dx/KA4mMjW0I8Twzn3/lsCxHTi316xrLhMHg25n/frWK2yCFL1WLAZRB2+XgUplwn0lr/lsQqapFQcA51i08+oNRfxodEvRJkZsTHT90MVxizhwpaRrm6iQ/gmf5y5oXezb4XDJmo1tTfwDNxBwm+kecHSgurobfoOdQGgMHCfnaQRCcczXrAFoPmv5hTgkZVvLQ=,iv:Gv2S2fu0j/0SaYIaE9LwmaoL+hYuiQTxS5xczQLplLg=,tag:Fr52k47PSIalErykTq43+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMnNpMnVZdFN0dW9qVGkx
            ZTIyRkN3c1dxbUdWQ3JoUGpuZUVzZXZvNnhBCjd1Z2dKK1RtKzF6N0Qra0krTWhT
            dUZQdTF2OFZQdVJTY0V2ZTNjckZoNTgKLS0tIExTQTdNSHlzdjhSYzVQcHNaemxp
            ajh5MnlVTWV2dm8xL0lreDh2SkhsdjAKvPjXhw92N3uF52aQtUkUkeJC8J5tq0xb
            Cd/M93UHuh2zbgqUndvYrsFFYiNbNUu4IRy0tn6gR3g7f8ToqNzqlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T20:30:58Z"
    mac: ENC[AES256_GCM,data:0mCtqvGIKA0OtJU4jMpbOcAtSeuHGYFvHGGFCMawlWJWDOs5jU+FcE0SR+aiv1Q9wrhdO2JuvdxzV3aV0dRGEHWELKHa8sp/u6SScGvLlYYgl+KK32cLYrdFyWjz+X0HzjQ1I4zB8/LluUB2eTydKmBYUn3q51BJdz1hdXP7EUY=,iv:Nz41/nO0hrM+3F7STZ/j/VTlEDaFJ/vlr5FyRAOsUqM=,tag:o4vRMOxgFgaxuY4rWz5MjQ==,type:str]
    version: 3.13.1
