apiVersion: v1
kind: Secret
metadata:
    name: jupyter-secret
    namespace: svc-jupyter
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:m8r/wTqdOTRxWIT9Q4Rx5rl09H8nHAgjdAagCdXxFy8=,iv:q/gZOIgcYO7xsRrQPnywMe0ueJDQBcrSufkythvW+BQ=,tag:ld40GGq3MUIfuGVVogeAsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK0M3QnF3SU9IdDJERzR2
            eGZLOTBuU0UzaXc1anV2VGhWallvbW5OYVZvCkIzYm8zbmVubUE4akM4TDNmeVF4
            d25uODdONzJtZHVWZ1QvaHhFam5QYXMKLS0tIGhCdHZOSVdCaGNvaDQ4M3NEdzVn
            dk9qejdNNGZpaXh3eGNwWmZBc2JXejQKWUZfyOU8h+HFdtbDsu8aPIQQpQU7Mewe
            PJ9uOB041ft6BbEwXGOxc6MIDJLxXxQ1yee9K56MUvuGTQUkgUxKFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T16:59:27Z"
    mac: ENC[AES256_GCM,data:1zV1bbQOQhsMzCvATAZSEOi07zna+TfYCK1hAJ7BocMlexMaXPa16LkmnsCrDs0gOrQ0y7UITxrEyAGR4qYJic6i8Q8QyCIy2tkimbQq3mWcGaaezlSMZT6dWYGgQkJvakh5k+GgntkaiUeQwvO8TFw3N6yQzCLQqfXBDRKyIro=,iv:eUYnUT4Qkw3CrKRNcpr84aewwmsT8K3vPlGvqjDWgzg=,tag:n9ir0hXRrpeoFnfT330Yiw==,type:str]
    version: 3.13.3
