apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3.eu-central-003.backblazeb2.com"
  credentialSecret: longhorn-b2-backup
  pollInterval: 5m0s