apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-paperless-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: "backup"
  groups: []
  retain: 72
  concurrency: 1
  labels:
    app: paperless-ngx
    type: hourly