apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "s3://s3.eu-central-003.backblazeb2.com/"
    "backup-target-credential-secret": "longhorn-b2-backup"
    "backupstore-poll-interval": "300"
