apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-target-nfs.yaml
  - longhorn-2r.yaml
  - longhorn-2r-immediate.yaml
  - ./recurring-jobs/
  - ingress.yaml
  - metrics.yaml
