apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2r
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - wk-1
          - wk-2
          - wk-3
          - media-1
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  replicaAutoBalance: "best-effort"
  dataEngine: "v1"
volumeBindingMode: WaitForFirstConsumer