apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2r
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  replicaAutoBalance: "best-effort"
  dataEngine: "v1"
volumeBindingMode: WaitForFirstConsumer