apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-gpu-system
labels:
  - pairs:
      app.kubernetes.io/part-of: intel-gpu
      gitops: flux
resources:
  - namespace.yaml
  - daemonset.yaml
