apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svc-media
labels:
  - pairs:
      stack: media
      gitops: flux
resources:
  - namespace.yaml
  - storage
  - bazarr
  - jellyfin
  - lidarr
  - radarr
  - qbittorrent
  - prowlarr
  - readarr
  - seerr
  - sonarr
