apiVersion: v1
kind: Secret
metadata:
    name: litellm-metrics-secret
    namespace: ops-monitoring
type: Opaque
stringData:
    LITELLM_METRICS_KEY: ENC[AES256_GCM,data:cT9PEZeTZaA09L700wpiVIC4TFCrGmfy2g==,iv:LHfEsGypGNcoom+tizs82A9KrK9s9O76UyqMEJoe2jE=,tag:XCy8aneNoDiyUkE6p4cBAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ0pCMGw5dEFLYmFsK0hU
            RHE2djE1VjdFbTlmeFJGTG9FRVJ5R2hXSGg4CkNDZ2ozUFBsWnR4UE9mdkhwL0RK
            SytOZ0ZhYUg2YVc2TVNNbHVEU1FGM3MKLS0tIGlTSE9mWVo1NnYvZytKTHdFcnpz
            aFZYZFhjQW8wTmNkNHdJb0ZUcExhbkkKWLMdpLstXDQ3bXN9k+JiNZsF64nn6IK0
            oieaqv5r98s6Rv/JF7vFhzDyF1sHV8JT0X/8QB+uqd7SHK//0poVNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T01:43:05Z"
    mac: ENC[AES256_GCM,data:gUi2QHMZnhWdj6E7jEwQo++2jY1jkPetlEYe4xYOt967RSvfDhNzbiHo89CxCD6LyRXL3ODv1BwTlrGbO9JuldfH0e+bP4Et82ads6AVlM8TmOGk7VSNqBRHLV0ePbRZZlta75Uo2wQ+cMYcWTkkTnkktKVuV/Nd05JBVKweMWs=,iv:EI2CQBrxDSfhlZ9WxMlT9Ld9H+kUgIrrMHWfOmUMbt0=,tag:5B7pn4j2agrCTP8LZkIXKA==,type:str]
    version: 3.13.3
