apiVersion: v1
kind: Secret
metadata:
    name: litellm-metrics-secret
    namespace: ops-monitoring
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:d4dal+y9jysM7M0wOBUvOnrrCfGW8Pg7W60vmQk9jm5AdHDo/vsEEHkk+Wl97bDAr3yoLJp/cj9de0EuYHo0sLCv3A==,iv:jBGow0+5ZKH3SNIv6Xl6/cQTOgd65uxjBIclOY4DkgA=,tag:bwAP5NFoJ75odzw2CwU9lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ0pCMGw5dEFLYmFsK0hU
            RHE2djE1VjdFbTlmeFJGTG9FRVJ5R2hXSGg4CkNDZ2ozUFBsWnR4UE9mdkhwL0RK
            SytOZ0ZhYUg2YVc2TVNNbHVEU1FGM3MKLS0tIGlTSE9mWVo1NnYvZytKTHdFcnpz
            aFZYZFhjQW8wTmNkNHdJb0ZUcExhbkkKWLMdpLstXDQ3bXN9k+JiNZsF64nn6IK0
            oieaqv5r98s6Rv/JF7vFhzDyF1sHV8JT0X/8QB+uqd7SHK//0poVNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T00:09:28Z"
    mac: ENC[AES256_GCM,data:lj2RlMnpyb0Ny830LY+dl2hFS/SC5H5W5AWVfsY6A48y63WZ/ZdLHyroxG5epOvUyRShWs/6raGhSVJOBFbLtj4XxEGcmb+vAMW9BkSZtcUe8kFk/U7ifTQ0WfixbWDZMGbatgKTgpF7xwWhb90gcLxU85EW/hvcXOLBsn4qQxs=,iv:ovt/w5lj1vn5IdyCZ6qJwg6JykPeBG8keVuIDPXmb/U=,tag:66EziqsbBiYh2oCRJAWpPg==,type:str]
    version: 3.13.3
