apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: ops-monitoring
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/trim-weekly: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 50Gi