apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-immich-library-data.yaml
  - pvc-immich-library-data.yaml
  - pv-immich-generated-data.yaml
  - pvc-immich-generated-data.yaml
  - pv-immich-db-data.yaml
  - pvc-immich-db-data.yaml
  - pv-immich-model-cache-data.yaml
  - pvc-immich-model-cache-data.yaml
