apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-generated-data-pv
  labels:
    app.kubernetes.io/part-of: immich
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-local
  local:
    path: /data/immich/generated
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media-1
