apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-data-longhorn
  namespace: svc-immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2r-immediate
  resources:
    requests:
      storage: 50Gi
