apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: svc-immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: immich-data-pv
  resources:
    requests:
      storage: 1Ti
