apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-data
  namespace: svc-immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media-local
  resources:
    requests:
      storage: 30Gi
