apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  namespace: svc-qbittorrent
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/trim-weekly: enabled
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 250Gi