apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-install
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system