apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/infra/cert-manager-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - kind: HelmRelease
      name: cert-manager
      namespace: flux-system
  validation: none
  