apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-root
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  commonMetadata:
    labels: { gitops: flux }
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      