apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svc-ntfy
labels:
  - pairs: { app: ntfy, gitops: flux }
resources:
  - namespace.yaml
  - ntfy-secret.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress-public.yaml
  - netpol-ingress-public.yaml
