apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: svc-ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:LcAdTV/jTqZdco7xTrDYraxnMpALH/wUWuDZSQNz6EV3iDH50rARcnCuuf8T42PrcFbMCAUmJq6+6Xxp3cHguIMdZLQSGC6c,iv:LiCEyOds+Nb4gVOi2cBs5MDJg2QIXXOMH3zAVmJyhe4=,tag:4z+mw4rIrxyMeckpaNVafw==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:z0B1LUyMy08gDoxmmlY1yikP9mnSZskcVDBiEjjyoEOLd+Dpm6BfFG/pDhXB17eslE0XYRtqTZ+B,iv:hPkVGSAB/Quqm1bLWSlN41qWO7l23DTahVTmqQxnnEw=,tag:p53UtOENOV/r+mV5EalWNg==,type:str]
    NTFY_ADMIN_PASSWORD: ENC[AES256_GCM,data:AFWv9Ye2JiOW5dg+faAFgCW1HxDGRt7rfQdghoH7,iv:0RhVClZ71Dm7xKA9ovr9G0ce7Ar1L0jvIvTbWK1vdxE=,tag:m9xTVV4Xx4ys+1Wj7Nx6LQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydzhJVWY4MFFYVUhtVS9S
            REVhZFB4WUcrYzlTajIzN28wSy94Y2NKd21vCnQ2RkpTMG01RytFdzR0b1NRVCtT
            cDVQQThMMnZ3MkpEeU04UEhjUU92bDQKLS0tIEVpNFhYYTNrU3ZHcVI5K2ZpN1d5
            eU5OQVZGZVJ6OWhKdC84U0Z4aEJsYWMKpiMYUagru9f/063Wh8ibK570BSIjVGl5
            wVGdrrGdBmy0WdkMeJiL1b4PdT7q657PdB5Hp2/1QsI++n8M5AKb0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:09:37Z"
    mac: ENC[AES256_GCM,data:/U4QihteymvmdaUmBWUqpwLuE0m2GI06GRbd6Rr5DyYBB0sJuFpp1KyCqjo+V/BLnvV1cx5HIUEt8VrVmwjx52DZAuHFu4EGd12AwU7tvyOHKceqV98lf8GbiWPrnxR674KPxn1VDFHwg6SkWeLHSDeuPqtUcjK5sNSWXG7dCn4=,iv:n5/NBaTTgkyLy0UqSQ9DzlHUtUVy3CsbHb83XMeM2G8=,tag:c1LDkzTR7gWMJC8T6fOxRQ==,type:str]
    version: 3.13.1
