apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: svc-ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:otybKr6aw9R739HUzRtDWsTklqcL4A6/Nzb4yi3m710kuqsB27cBgXv4a4shXUmkMXO7UOWyL5oH4dXZQDuYINjsqZmgwsX1t23wLtg7GHbe2pxLuIZO/LIOnG7JPOw38IVS5kL5XRN6sjzyEjJnE/aXEvSQgD6fEzPComUeNaU7W/60bfsxSmO3l6kW+XEjWI5Gd5DaTg==,iv:OG12OO5613VhnBMzbcikdVOigwD7aHVF95HbB5duPYU=,tag:3Fnt9pBbJStL2n/bbqYd1Q==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:fJRNHL7ZuMR7ZnCovRH9MHFZ7wR9EXQWwEeWpcbzU+ep07fp5rT4GE82/6BWRbF35YXGgVu3T7DqxRfIqwCDwIWIsM3an5j14jdoluBIIL7jDzqkcBrwHO/+eal07yPEYhwXUWx26iE2gJGGn+4dlCdcj2w=,iv:vgn3l3Xrb+gCoYVWU+m5nP/oHKPGoYUwZm66BQnwQZI=,tag:+26YOIBtXJzrGSUryHJNzg==,type:str]
    NTFY_ADMIN_PASSWORD: ENC[AES256_GCM,data:LnE0vZrup16QV4lrd7bfvpJ9qL8x8NfBCkMDd+zw,iv:SBSUGsvJWBKdIHLVQcDZ+Rygu2He+yqKhHi3NDIIwyw=,tag:GlsngBLXRtRyy0XyzVewqg==,type:str]
    NTFY_MEDIA_BACKUP_PASSWORD: ENC[AES256_GCM,data:lMfKOJzRrc3P4zHgDxlHUPlPcf8Y8QT44+oR/1pXuw==,iv:mvRkNRYSv30/UYqo/Gp1uqUwyBck02Cfthl0RMeXHXI=,tag:LFTjGnI80C2PM1RxiRuMCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K20rNzM4S25yNHF5czhm
            YisvMi80dlkyVmliZmdnVjliWkVQa3BaMjNvClV3SFdiWWtwbDFUNldWYXZmajFP
            cUR6NFRKbDhOajdkQXlMVVp5SVd1Q0UKLS0tIEl4MGlrTUhSdWlWNUFuT3JaU3Rq
            QlNaZWV2clFUc08wdTR3V285bG95N2sKYvZomgrvwG/1XU9zkN6+JUdqTq0LdKx6
            cGFRTZVAPx5Of1U+730Ttv+AbQRzGvY1vJG5FFBbolnmVrFWg18l/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:29:03Z"
    mac: ENC[AES256_GCM,data:xvlzWo2YSe11+hZ/BhMqTgYMFEOAXDPsJwiXTdw5d7dfNpqK1T13UyBW55HhCqu7lWVP4PuMYhp+1YSzUzup+MWybwhyONzif+6NqCEe3XjnaQC2El4c/0icZJ4XO3AC1CaFQy35YoCQKFybgzuZ19o3x6WOxg3yaHF06l1FXsY=,iv:Qn211pqHQoZKWL1esV/n2AiIUkcqxH2NYQWlMqQDYFc=,tag:sq4xpZJ5I/dtXA85CfkguA==,type:str]
    version: 3.13.1
