apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: svc-ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:Z+HiIe7IC3eXApeTzuLonPXVaiqaqa3l6sTU2TIaCZcozu7cvyRJxE6vRjzC5YF2e58W+Gb5beVEOQYhHVWpaX0bjMNYeAKqWokeYAv05xw2oZaScEeQGVb7CkLU2bMc24r18pK1DRh6s2YS4LDoLWrUn736EamgZ8ZD3mOqXPARvSvp4a5DYt3yQdbTs1YFLHPmWLUW+rQ4QV3IUE3RJAjMOQQt51K3wKBLZMNdMFZ/S8XZ7I73sSqmNqssZ2kdoYmbJ7wABU5V0YhqeS7RnrCIr6kEm9CRTXlYtElNJixJ,iv:0n22Fb5AjGKlsjfCmK5n+KEcvmVnCUn8XWRPpadhEbM=,tag:7oBzBYkdy6rYpeAy76Ujvg==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:8aKsikpbQuRMW63+QFOpAJ0ugni5XJn7A07SC5dPDjsBKoDfsr7iKkvTwKRueNxdxg5EvC5pSSVdKG99ssusqPcGPRsn0We77ADDehJdzw1n8y1V6ITuyYobsIENALRiYQYwOg3YslHs3Ab0wBI9ASdC0LDcXFlaAGmalwx8NhOSxrciNCm2GRYvetVMxLkjWqp9BRvBUMeeQ6U/tC/dm58NDDPDtULtPxMIkw==,iv:2QGD+HYM/TsE7fzCBwNu/RdDmUhT5pApU0p0KzRV8aM=,tag:HTwv18HPU9/EhFRkytOYbA==,type:str]
    NTFY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Fj1qe70aUfA2IWa4l4vAaMv72QL4IHYXctZEMfjS,iv:GDmrDsnIKcTCSaO3san14pQdb/PJCbT6p38qFyuOaYY=,tag:2Uam1jN0YSoPt/Gp+cWugg==,type:str]
    NTFY_MEDIA_BACKUP_PASSWORD: ENC[AES256_GCM,data:b6IDfVBYEzLGLy9jtcUCJ+7ZNlr0ZCQnK+HDvPY2fw==,iv:r05u7Mq1w5xpG5fQ9W+7ZDPCfhh8ju/3BDNgR3/6tqc=,tag:w86cu+NWhZgOJerxsJBBEg==,type:str]
    NTFY_TRUENAS_PASSWORD: ENC[AES256_GCM,data:f2kwXtYI12sqg9T9h759/wrtD6CvFzZgKSZnrNdDDQ==,iv:pA0xWhPFExXYa0IqzTHSCgogERK25vH2nll2kq+Q4ec=,tag:ctNR4MWUSlymkxXQ9E98sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRXFxK1ZYRXFEZ1RUMjhU
            Y0xqTFJVNGdWWDd4YVFIZmNzd1pEZVdCN1hRCm5KdTZINklHNVE5N0lpTU9SdW5B
            R201SmwzZklpQ3VCNEt4eFFpR1dRL0EKLS0tIFZjRS80SmtWaHdBTmVEVnV6TmF1
            bWo1Ykh4dkdsTG9hSUlRNkk4Qjc1OTAKaw8vsQonO5iGfL0ZEPI2MiGcZ6Y7ufoz
            WXSSajG+46C8JmYCSnLfzRAr4PielcHObuqKD1FXc0ZTJjJzxBq4nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:58:42Z"
    mac: ENC[AES256_GCM,data:Td0rJsB2CRwSb9p+koUO8pTnlCSB5qM6o4unqV1BxnNgCk+BKlDGL0N2e5/0Q/Ay6iVgj1Cf51jDdH1t/blC3UlHe5KEy6Yl0JN4BfPzxsMcGx2uJUN/4dFPkj/gT3aWn1OG+IvaJutV6N4VB2fmzQ+mhQbt2cdTcwtkovcJa68=,iv:N/tq0uJ3J80JAbs+O5TSRhT249tchy0NaelPIgUcv5k=,tag:ApD+5y9cM8+VKsJLSnmPdg==,type:str]
    version: 3.13.1
