apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-30
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: ingress-30
  values:
    controller:
      kind: DaemonSet
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      ingressClassResource:
        name: nginx-public
        controllerValue: "k8s.io/ingress-nginx-public"
      ingressClass: nginx-public
      ingressClassByName: true
      watchIngressWithoutClass: false
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.30.151
        annotations:
          metallb.universe.tf/address-pool: pool-vlan30-public
      publishService:
        enabled: true
      config:
        use-forwarded-headers: "false"
      metrics:
        enabled: true
      extraArgs:
        metrics-per-host: "false"