apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: svc-homepage
data:
  bookmarks.yaml: |
    - Quick Links:
        - GitHub:
            - abbr: GH
              href: https://github.com/FabianLiske
        - Compressor:
            - abbr: IC
              href: https://compressor.intern.rohrbom.be/
        - Immich Photos:
            - abbr: IM
              href: https://immich.rohrbom.be/photos
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  proxmox.yaml: ""
