apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: svc-homepage
data:
  bookmarks.yaml: ""
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  proxmox.yaml: ""
