apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svc-homepage
labels:
  - pairs:
      app: homepage
      gitops: flux
configMapGenerator:
  - name: homepage-assets
    files:
      - shaded-landscape.webp=assets/shaded-landscape.webp
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - homepage-secret.yaml
