apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: svc-vaultwarden
data:
  DOMAIN: "https://vault.rohrbom.be"
  WEB_VAULT_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  SIGNUPS_VERIFY: "true"
  SIGNUPS_VERIFY_RESEND_TIME: "3600"
  SIGNUPS_VERIFY_RESEND_LIMIT: "5"
  SENDS_ALLOWED: "false"
  EMERGENCY_ACCESS_ALLOWED: "false"
  LOGIN_RATELIMIT_MAX_BURST: "10"
  LOGIN_RATELIMIT_SECONDS: "60"
  ADMIN_RATELIMIT_MAX_BURST: "10"
  ADMIN_RATELIMIT_SECONDS: "60"

  ROCKET_LOG: "critical"