apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-local-data-pv
  labels:
    app.kubernetes.io/part-of: media-stack
spec:
  capacity:
    storage: 1600Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-local
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media-1