apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-local-data
  namespace: svc-media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media-local
  resources:
    requests:
      storage: 1600Gi