apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-data
  namespace: svc-media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: torrent-data-pv
  resources:
    requests:
      storage: 900Gi
