apiVersion: v1
kind: Secret
metadata:
    name: unifi-mcp-secret
    namespace: svc-llm
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:clQTzCa8yck1W36kqpYdOCUkq7vit6JiTWDOng37UDw=,iv:TpLH3BtiaLtGNa9ICZdTT/mu9FmV3WADaKiqUVBMubU=,tag:+rH6EqvMP4DiXa2WLCaaSg==,type:str]
    MCP_AUTH_TOKEN: ENC[AES256_GCM,data:90IGqvoEr5OBPhEACHPm8UTXf43GBd0kNxVCdQAlZBe/NkFlNa+hvP1G7OAwWNjGupimfUhUN0rirkvscJizUg==,iv:ba8hCyhD8TFp+B+it5GmjGkVo1uvbXNi4QLrZkDzDNo=,tag:etsHgatAs0iKfCQIckWqzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZGpEc0M3UGFGUzUySm8y
            enJiRnBPMU9kZmovSHhPNTBZUE1iRER6OFNvCkIyMS9jeWVqMzQ0R2p3eXJZRXZT
            VGhlZ1VCbS91OWVKQ0s2WnhvOE5SQTgKLS0tIGx6Zk1HYzhKK0ZaYkhvQUp5ZXBY
            cjQzdUNsSkMvb21EajM2RDIxQjdzOGcKc/LvQz44qQ3bZVipsgl9sIv4MgFM4c7d
            Hlif5nT/yszAVAJHC+iiOY6WcOnvpDNG/4vAynWzASvv4k/7vA3nPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T15:44:44Z"
    mac: ENC[AES256_GCM,data:UZHOQ3XBQLnXNxqZ29dqV9q+UGR35IjnrFkrprvPTvCIIAc9NHG9thF7OGIB18/qE2ukcnYMQsrR0uhXLRJ3Ty/WGCU7wF9mUI6f9kTfQQH7rYVL7LskGL2BzJrFVlo2fPMDcwPA+/XiIkIRYJU1aT/fi5NA63Epi0pUpE+xbhk=,iv:cxukx+PZmBORfrd2JMA0+cwSOvS40vgqbN/gzmhMsXQ=,tag:UITBv48Y9i/q8vY9RBikXw==,type:str]
    version: 3.13.3
