apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
    namespace: ops-monitoring
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:gV0D2aU2qs9w0c5BxqM7uxdX,iv:79QHFlRJFa40Lsc9Ju57Lrb7AGapGYsIOyVsFQ2b1/s=,tag:DgCdmOQa02kZdHh04webIg==,type:str]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:YH5ajFmf1Ng=,iv:bc1nC1vkujlqk/MQLtNB6IG1kdIaej4wbi87HFU8iGE=,tag:/Lqt4WB5LzeYkNrlrUcghQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:2BfOnKIyC6BBCxnvq3Sfg9bRcmvzErw6w+mXgH6+opCiecAV++TsOcP2CoQogtYEV3X3uUeQ81OyIVjcnPQaQQ==,iv:KwhuQTP1rfi09HL2NYUOQWcwTX2iYFfL15kvTpEjcww=,tag:3+Y+ZElvNW7uZl8oY7a6TA==,type:str]
    UP_UNIFI_DEFAULT_VERIFY_SSL: ENC[AES256_GCM,data:+8e3EZw=,iv:UmHDUcCvW/zGqNVuA+hwAbuP2n7NNTRoaiahiq2l1N0=,tag:DF3RxekrjtX2XZPbNAKBCA==,type:str]
    UP_UNIFI_DEFAULT_SITE_0: ENC[AES256_GCM,data:ub23,iv:iRfqPo5fZJJrXn92N80Q9g5RJll4bBpGpymptm5qelM=,tag:S+WdUqYCylgoOLKbfT8n5A==,type:str]
    UP_UNIFI_DEFAULT_SAVE_SITES: ENC[AES256_GCM,data:KQk8Rw==,iv:+F0EkRPIJiR1wqteRjrr4dv/ibCjNu1zShvqBapD9kk=,tag:3NyWbtuutGN49VJMFBWGIw==,type:str]
    UP_UNIFI_DEFAULT_SAVE_DPI: ENC[AES256_GCM,data:k3dS4g==,iv:a1Df6V41KADtdV3fQbAQhYLBHp5ivIOOWyjpMjxuEwo=,tag:gvcWqt1WYH223sSrAH2y3g==,type:str]
    UP_UNIFI_DEFAULT_SAVE_IDS: ENC[AES256_GCM,data:vKJIkig=,iv:OLPROiwl0Jl8Yj51XYFCLPo0yd3oIgATrFaRRI8QuUo=,tag:HeQMfYrzwVO4uAv3N9/ySQ==,type:str]
    UP_UNIFI_DEFAULT_SAVE_EVENTS: ENC[AES256_GCM,data:x0kH4R8=,iv:x6ivn1Cnu9UrD2fgDOUEFAkPoPimdl2FJL3HxGOWEag=,tag:5P2dh5mOTDSQjOixQY0VUw==,type:str]
    UP_UNIFI_DEFAULT_SAVE_ALARMS: ENC[AES256_GCM,data:XKR2oOA=,iv:gLyZfhhqEQ+NvhK/6Z38w4zoTKiph1sLXNNzKTTK39c=,tag:ZHasQ1EROXikkJz7OXzEXg==,type:str]
    UP_UNIFI_DEFAULT_SAVE_ANOMALIES: ENC[AES256_GCM,data:MZm+ZN0=,iv:JhNGUDaDW62jvT0lsWUHY/uj2YbjmXjecgtb5uxttVQ=,tag:EJ/5kBNHSStZEFkTtts2yw==,type:str]
    UP_PROMETHEUS_DISABLE: ENC[AES256_GCM,data:Uo96yZY=,iv:fDZJW1Epk7h/R/94CxgtMiw+k29dv49wrkWap6b9TWM=,tag:bP5m0IuOs7uN68ZUa15eBA==,type:str]
    UP_PROMETHEUS_NAMESPACE: ENC[AES256_GCM,data:M3XC5nY4ryO3ITY=,iv:5QrzdSXiHiaNiXDmxSghVEbtLl6kgTQDp8fdIUIKfOU=,tag:1/4Mq7z8f9JSAGvNPFqqMQ==,type:str]
    UP_PROMETHEUS_HTTP_LISTEN: ENC[AES256_GCM,data:cPWLk+YM0gsTQ+4/,iv:+DLbmL9pEPlo7PJupZMCEwXp4roAvuGxdrBs3/yrwO0=,tag:vseZ+fL9qiTLly5CyyaRbQ==,type:str]
    UP_INFLUXDB_DISABLE: ENC[AES256_GCM,data:SIUsbg==,iv:239DsoD4gilZjox/VOAMWghMDGhdKaF9HKrfTijrAZU=,tag:nQS1+SZl0N6SiAvnmIzlEA==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd2hiVWZzcWxuZ2thRkIz
            MlVoWW55ZW1Id0tLbTViUHhpSURiMDlEUjEwClRKaU42ajk0QU9kYmx6MnZ4cWpS
            WTFZNEJpc3RPNmQzditSODU0UUhYYUkKLS0tIGsxSGZqK3Frc05YMGZVU1R3U3FZ
            NitycllNQllBektIQmxGT1h2T2o5djAKm3t4pS4xViBIYY0Pwu42bg6j91VtG/C5
            acE56SPoFgFWoYvFD7a9WKQIpgEEvxwLLrRyU0TsL3jmnBy7zEZ1zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:41:35Z"
    mac: ENC[AES256_GCM,data:q4ThaeeRn7yv+jMP276qo1ER1td1ljZl2Et5Dba9BqdYySs3rEk6cTBwLFH41fv8uSKiMDRSFlllkJ935AOWtU0GAeEDkCS7Wf+YiEXAxxk/rNzpO4JssT0GczSf7FqOP/p/NIKFVc1itlAHd6bXD2hYFEomZbZ7FjjAQYPj5jA=,iv:7/G07Jj73Yp8ayIxtpcAIvPvzYUiwbDcyFmB5shHf+0=,tag:5343XfMk37lNtS68WPTKsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
