apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-broker
  namespace: svc-paperless-ngx
  labels:
    app: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: broker
  template:
    metadata:
      labels:
        app: paperless-ngx
        component: broker
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: init-volume
          image: busybox:1.28
          command: ['sh', '-c', 'rm -rf /data/lost+found && chown -R 999:999 /data']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: redisdata
              mountPath: /data
      containers:
        - name: broker
          image: docker.io/library/redis:8
          volumeMounts:
            - name: redisdata
              mountPath: /data
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: paperless-redisdata