apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: svc-paperless-ngx
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 2Gi