apiVersion: v1
kind: Service
metadata:
  name: paperless-db
  namespace: svc-paperless-ngx
  labels:
    app: paperless-ngx
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    component: db