apiVersion: v1
kind: Service
metadata:
  name: paperless-tika
  namespace: svc-paperless-ngx
  labels:
    app: paperless-ngx
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
      name: http
  selector:
    component: tika