apiVersion: v1
kind: Service
metadata:
  name: paperless-webserver
  namespace: svc-paperless-ngx
  labels:
    app: paperless-ngx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    component: webserver