apiVersion: v1
kind: Secret
metadata:
    name: mampftracker-auth
    namespace: svc-mampftracker
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:YUvZJw==,iv:94es5112hasplmi8Lv/PMOTnuYKtzGGFg9GrcpnpKQ0=,tag:qFLDmmnB8+afHZydlU5wDg==,type:str]
    password: ENC[AES256_GCM,data:qm4mpGdkEK/zeVTMWK3xjUMqTQjVE5MCHLo5fjSirOk=,iv:oV2XzdckABJKW1vck0IwrWUtUiSl2x8PTzCJX4E7ohk=,tag:UklH0P/LIW4u3zd9ZpwmuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q2FuOHU0RE1CWFhvZG5o
            emJpMWx6QzVVUkJPM1dQYVJSVGUzQVAzbGdjClR2UFhwN1pmYVRVOGxDK3hHcGNX
            NEpxbkpvT3ZiY1dVNWxqcjZtSnpudGcKLS0tIGYyaUxCV1grcW5YaEpFWk54aTVt
            Y09zTldTWW5uZG9qWDZpdnMzeS9PODgKB5wR49iLBfllWm0kziMPix/gSY2AQnkc
            rlg6loY9d+ZDRzGJb6x/UfxPzyud0baKbmHK7Uc4kaZ4vJKPSIKcOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T10:13:14Z"
    mac: ENC[AES256_GCM,data:BZrqtmbxVGCqfFlS0UeUlNFdgn9mWX1tc9v1BKSNqgSCj5PzFFjs5+I8g8d/bnrWFIJM8eCfLLCmpg1s8q0Y+33W9GnnjCNRSIwvCCavSdZ6YK+gc+SsCxlPDmAbza5VU8rhLlcBqbEWlntq8WkgsbxFCB6DQRgGy0IBvBwSNHM=,iv:FFI8duKaYcDGOYlABL5jUCxNnmwUEPDabtYvie8DKWU=,tag:rO7Uj6s9FTgc2W/VKOAdWg==,type:str]
    version: 3.13.1
