apiVersion: v1
kind: Secret
metadata:
    name: mampftracker-auth
    namespace: svc-mampftracker
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SEPY8Q==,iv:voU3GIkkc2cPcykdcbw2E34CK1wqWYItyo4Am2HVyos=,tag:44wqPhC4c/xM1diwFuVpvg==,type:str]
    password: ENC[AES256_GCM,data:ZFuPRXnTqASfwfr6BxrZMjM2zq5ZDmVO62i39X3CrCQ=,iv:8jPZG8kt5nOx8x/xurcC4cxtUyRIeFZzMoTnp7lf7Us=,tag:x7wBLDAFPnrnq07eNa0YHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaUg4ZHZScURVL3pNV29M
            ZkNEbGRlKzYzcHRGZGRSVXJiemJXZE5WTTJJCmNJR1NMVVNHRmIrSmVlbFNMaUhE
            dVE2SUo3M0ZVc1hYYTcwZktobjlCTkUKLS0tIHZ3emZDL0VRTWlMenJIWERzMEVC
            cmNWeDhaaUZkUW5yV084UGFxZUR5bDAKaaB1q5M8Z9HcwsTidMbf7XjQJwy6qMfb
            4CBp2vIBuQA68fQhea1ZJ6FxKoayWVbWO/IILDxtDALUTo+L/Wbr7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T10:33:46Z"
    mac: ENC[AES256_GCM,data:zFyO88zVJ4SkX01VoOnlPBnnMHP1O9SAYY5IjdIRQWN0PCBnw8PgW9QzUQbTlhezLT6VZc0iywLN1yaV6OMSWOqzRxTGyLkxTrOyGROyvlp4E7nNfKTmXIZxS7NovVYg0MVPnorLA9/G30risbhtVOfZQeHoXHcY4jpf2WbY/1I=,iv:B/luuRzaFN0/KsalX9UNMlUtW+Y3bIMxhZQ5kmvRiNw=,tag:5dI4O61Tnr84KiLuFt5v8Q==,type:str]
    version: 3.13.1
