apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: svc-trilium
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 5Gi
      