name: Build and Push Telegraf Image to GHCR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'monitoring/controllers/telegraf/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/fabianliske/k3s-homelab-cluster/telegraf-custom
          tags: |
            latest
            ${{ github.sha }}  # Zusätzlich SHA-Tag für Versionierung

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: monitoring/controllers/telegraf 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64