name: Build and Push Image Compressor Image to GHCR

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-image-compressor-image.yaml"
      - "containers/image-compressor/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/fabianliske/k3s-homelab-cluster/image-compressor
          tags: |
            latest
            ${{ github.sha }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: containers/image-compressor
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
