apiVersion: v1
kind: Secret
metadata:
    name: ghcr-cred
    namespace: svc-image-compressor
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:D/PJR8SzobG+uzc4ga3wveYJB2jAumIpuLsCcbVHJx4HtjHW7lYdAihvOh0c3TvfxqzO/M6StKqesOk45Kpuog8nMQnq6zcznhZxh21ISQlIIReskWj/G7tQV4iX+m5CGLIWCNhetVY9xy4jK72787Q2GAOQs9k+lQ/ZPJ5NCsHKKdHO8E1/66m0EhOp76ORajAmvbgZEl+NH96SduNOX13kaypHEMafuSHV9kbe9x5hOL8BE/UPDzN4JHMh35xNQNnWPwkQ33q4KOWw8BpeGcO9uWbbd8khCbaOTmcurVx01GZnavy1l3I1CLzTzxPPHbfkfX+bmi05QlxFZSF4wep8aX8sth5toIbp6rI=,iv:EGwIz5VBx9PpMFiNreVvDFZKaqe7EyT1XPXD32leGPo=,tag:wnjzGM7cgdJc71PmTImbyQ==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR00vWEZCU0RhcG5JeXND
            N0dKR0JmdGhvN21Ka1hYa3NGMjZNd0dBcGtNCi9RcWtFSTZCTURYMmRPYnJlaHpi
            UUF5Zk13TWJibVFEYkdrb082Tm5JcnMKLS0tIEJJWERMR1dhQndQSFpYdW9JUWRq
            L2NFNFJaRVlGSkUzb0k3TFZYanlQeFUKXywjO5yGk9ei/uh5Hz3tTjHu9rcRMzL9
            +et4300dd0e+pw53EI88SIU1x+qumHMo+6QhrPJrapexQoFVAYDnCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T14:22:33Z"
    mac: ENC[AES256_GCM,data:JFwUH8qSdAp8ZahN9PXjzqwT1y6mu/Ta5dpdPDzpDL8CSVYcRhIe9R8kpUjt+CUFFPI1dUGtzFj1bDSSKdf4ajswiYwuPDNO8c7MiLFalt3RxT3VtG8/HmHdqYui4iJ9zySbNV0Y+MoEYbhCXfIqs4A1FsgFGAk6+EJFEL3Vpjc=,iv:QNVnQNpK09kSV5tx6qrvP23vif1w0wqxfRZo5sabnGI=,tag:2yq6i1ulcuJAuUPtEEbXow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
